In [1]:
import numpy as np
import random

n = int(input('Введите размер матрицы: '))
values = [-1, 1]
A = np.zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        A[i][j] = random.choice(values)
print(A)

s1 = 0
for i in range(0, n):
    for j in range(0, n):
        s1 += (A[i][j] * A[(i + 1) % n][j]) + (A[i][j] * A[i][(j + 1) % n])
print('Сигма 1-ой матрицы =', s1)

print('Новая матрица: ')
B = A.copy()
B[random.randint(0, n - 1)][random.randint(0, n - 1)] *= -1
print(B)

s2 = 0
for i in range(0, n):
    for j in range(0, n):
        s2 += (B[i][j] * B[(i + 1) % n][j]) + (B[i][j] * B[i][(j + 1) % n])
print('Сигма 2-ой матрицы =', s2)

dif = s2 - s1
print('Разница сигм =', dif)
if dif <= 0:
    C = B.copy()
else:
    T = 0.8 # вещественное число от 0 до 10
    W = np.exp(-dif / T)
    print('W =', W)
    P = random.uniform(0, 1)
    print('P =', P)
    if W > P:
        C = B.copy()
    else:
        C = A.copy()
print('Полученная конфигурация: ')
print(C)

Введите размер матрицы: 10
[[-1.  1.  1. -1.  1.  1.  1. -1.  1.  1.]
 [ 1.  1. -1. -1.  1. -1.  1. -1. -1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1. -1.  1. -1. -1.  1. -1.  1.]
 [-1.  1. -1. -1.  1. -1. -1. -1.  1.  1.]
 [ 1.  1. -1.  1.  1.  1.  1. -1.  1. -1.]
 [-1. -1. -1. -1.  1. -1.  1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. -1.  1.  1.  1. -1. -1. -1.  1.]
 [ 1.  1.  1. -1. -1.  1. -1. -1.  1. -1.]]
Сигма 1-ой матрицы = 4.0
Новая матрица: 
[[-1.  1.  1. -1.  1.  1.  1. -1.  1.  1.]
 [ 1.  1. -1.  1.  1. -1.  1. -1. -1. -1.]
 [ 1.  1. -1. -1.  1.  1. -1.  1.  1. -1.]
 [ 1.  1.  1. -1.  1. -1. -1.  1. -1.  1.]
 [-1.  1. -1. -1.  1. -1. -1. -1.  1.  1.]
 [ 1.  1. -1.  1.  1.  1.  1. -1.  1. -1.]
 [-1. -1. -1. -1.  1. -1.  1.  1.  1.  1.]
 [ 1.  1.  1. -1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1. -1.  1.  1.  1. -1. -1. -1.  1.]
 [ 1.  1.  1. -1. -1.  1. -1. -1.  1. -1.]]
Сигма 2-ой матрицы = 0.0
Разница сигм = -4.0
Полученная конфигурация: 